(arguments (identifier) @markid)
(assignment_statement (variable_list name: (identifier) @markid))
(binary_expression (identifier) @markid)
(bracket_index_expression (identifier) @markid)
(dot_index_expression . (identifier) @markid)
(expression_list (identifier) @markid)
(field value: (identifier) @markid)
(for_numeric_clause (identifier) @markid)
(if_statement (identifier) @markid)
(method_index_expression table: (identifier) @markid)
(parameters (identifier) @markid)
(unary_expression (identifier) @markid)
(variable_list (identifier) @markid)
