(column_definition name: (identifier) @markid)
(field (object_reference name: (identifier)) @markid)
(field name: (identifier) @markid)
(term alias: (identifier) @markid)
(relation (object_reference name: (identifier)) @markid)
(relation alias: (identifier) @markid)
(create_table (object_reference schema: (identifier)) @markid)
(create_table (object_reference name: (identifier)) @markid)
