--================================== options ===================================
vim.opt.clipboard = "unnamedplus"
vim.opt.colorcolumn = "80"
vim.opt.cursorline = true
vim.opt.ea = false
vim.opt.expandtab = true
vim.opt.ignorecase = true
vim.opt.list = true
vim.opt.listchars = { tab = '│·', extends = '→', precedes = '←', nbsp = '·', trail = '·' }
vim.opt.mouse = "a"
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.scrolloff = 5
vim.opt.shiftwidth = 4
vim.opt.showmatch = true
vim.opt.sidescroll = 5
vim.opt.signcolumn = "yes:3"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.switchbuf = "useopen,uselast"
vim.opt.tabstop = 4
vim.opt.termguicolors = true
vim.opt.syntax = "on"
vim.opt.background = "light"
vim.opt.grepprg = "rg --vimgrep"
vim.wo.wrap = false
vim.env.EDITOR = "nvrl"
vim.g.mapleader = " "
