(argument value: (identifier) @markid)
(binary_operator (identifier) @markid)
(extract_operator (identifier) @markid)
(for_statement (identifier) @markid)
((identifier) @markid (#match? @markid "`.+`"))
; (default_argument value: (identifier) @markid)
; (default_parameter (identifier) @markid)
; (dollar . (identifier) @markid)
; (equals_assignment (identifier) @markid)
; (formal_parameters (identifier) @markid)
; (if condition: (identifier) @markid)
; (left_assignment (identifier) @markid)
; (pipe (identifier) @markid)
; (right_assignment (identifier) @markid)
; (subset2 (identifier) @markid)
; (subset (identifier) @markid)
; (unary (identifier) @markid)
