(aliased_import alias: (identifier) @markid)
(argument_list (identifier) @markid)
(as_pattern_target (identifier) @markid)
(assignment (identifier) @markid)
(attribute object: (identifier) @markid)
(augmented_assignment (identifier) @markid)
(binary_operator (identifier) @markid)
(boolean_operator (identifier) @markid)
(comparison_operator (identifier) @markid)
(conditional_expression (identifier) @markid)
(default_parameter (identifier) @markid)
(delete_statement (identifier) @markid)
(dictionary_splat (identifier) @markid)
(dictionary_splat_pattern (identifier) @markid)
(expression_list (identifier) @markid)
(for_in_clause (identifier) @markid)
(for_statement (identifier) @markid)
(generator_expression (identifier) @markid)
(global_statement (identifier) @markid)
(if_statement (identifier) @markid)
(import_from_statement name: (dotted_name (identifier) @markid))
(import_statement name: (dotted_name (identifier) @markid))
(interpolation (identifier) @markid)
(keyword_argument value: (identifier) @markid)
(list_comprehension (identifier) @markid)
(list (identifier) @markid)
(list_splat (identifier) @markid)
(list_splat_pattern (identifier) @markid)
(nonlocal_statement (identifier) @markid)
(not_operator (identifier) @markid)
(pair (identifier) @markid)
(parameters (identifier) @markid)
(pattern_list (identifier) @markid)
(return_statement (identifier) @markid)
(set_comprehension (identifier) @markid)
(slice (identifier) @markid)
(subscript (identifier) @markid)
(tuple (identifier) @markid)
(tuple_pattern (identifier) @markid)
(typed_default_parameter (identifier) @markid)
(typed_parameter (identifier) @markid)
(unary_operator (identifier) @markid)
